# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: ğŸ§¹ Remove trailing whitespace
      - id: end-of-file-fixer
        name: ğŸ§¹ Ensure files end with a newline
      - id: check-yaml
        name: ğŸ Validate YAML files
      - id: check-added-large-files
        name: ğŸš« Prevent adding large files

  - repo: local
    hooks:
      - id: prettier
        name: ğŸ’„ Format files with Prettier
        language: node
        entry: prettier --write --ignore-unknown
        types_or: [css, javascript, json, markdown, yaml, scss]
        additional_dependencies:
          - "prettier@3.1.1"
          - "@shopify/prettier-plugin-liquid@1.4.0"
