name = "Blog"
uuid = "c00e6a3f-df91-4e85-b3e7-94e293d6ccf5"
version = "0.1.0"
authors = ["Stefan de Lange <langestefan@msn.com>"]

[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
Bonito = "4.2.0"
Colors = "0.13.1"
FileIO = "1.18.0"
OrdinaryDiffEq = "6.108.0"
WGLMakie = "0.13.8"
