[project]
name = "day-ahead-prices-nl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.0",
    "plotly>=6.5.2",
    "ruff>=0.15.0",
]
